// Mock data for the user dashboard

export function getUserData() {
    return {
      id: "user-1",
      name: "Alex Johnson",
      initials: "AJ",
      title: "Senior Frontend Developer",
      email: "alex.johnson@example.com",
      phone: "+1 (555) 123-4567",
      location: "San Francisco, CA",
      profilePicture: "/placeholder.svg",
      about:
        "Passionate frontend developer with 5+ years of experience building responsive and accessible web applications. Specialized in React, TypeScript, and modern CSS frameworks. Looking for opportunities to work on innovative products with a focus on user experience.",
      socialLinks: {
        linkedin: "https://linkedin.com/in/alexjohnson",
        github: "https://github.com/alexjohnson",
        twitter: "https://twitter.com/alexjohnson",
        website: "https://alexjohnson.dev",
      },
      skills: [
        "React",
        "JavaScript",
        "TypeScript",
        "HTML",
        "CSS",
        "Tailwind CSS",
        "Redux",
        "Next.js",
        "Node.js",
        "GraphQL",
        "Responsive Design",
        "Accessibility",
        "UI/UX",
        "Git",
        "Jest",
        "Cypress",
      ],
      education: [
        {
          institution: "University of California, Berkeley",
          degree: "Bachelor of Science in Computer Science",
          startDate: "2014",
          endDate: "2018",
          description: "Graduated with honors. Focused on web development and human-computer interaction.",
        },
        {
          institution: "Coding Bootcamp",
          degree: "Full Stack Web Development",
          startDate: "2019",
          endDate: "2019",
          description: "Intensive 12-week program focused on modern web technologies.",
        },
      ],
      experience: [
        {
          company: "Tech Innovations Inc.",
          title: "Senior Frontend Developer",
          startDate: "Jan 2022",
          endDate: null,
          description:
            "Lead frontend development for the company's main product. Implemented new features, improved performance, and mentored junior developers.",
        },
        {
          company: "Web Solutions LLC",
          title: "Frontend Developer",
          startDate: "Mar 2019",
          endDate: "Dec 2021",
          description:
            "Developed responsive web applications using React and TypeScript. Collaborated with designers and backend developers to implement new features.",
        },
        {
          company: "Digital Agency",
          title: "Junior Web Developer",
          startDate: "Jun 2018",
          endDate: "Feb 2019",
          description: "Built and maintained websites for various clients using HTML, CSS, and JavaScript.",
        },
      ],
      stats: {
        upcomingAssessments: 2,
        jobsApplied: 15,
        savedJobs: 8,
      },
    }
  }
  
  export function getUserDocuments() {
    return {
      resumes: [
        {
          id: "resume-1",
          name: "Software Developer Resume",
          description: "General resume for software development positions highlighting my React and frontend skills.",
          createdAt: "2023-01-15",
          updatedAt: "2023-03-20",
          fileUrl: "/files/resume-1.pdf",
        },
        {
          id: "resume-2",
          name: "UI/UX Focused Resume",
          description: "Tailored resume for positions that require strong UI/UX skills and design sensibility.",
          createdAt: "2023-02-10",
          updatedAt: "2023-02-10",
          fileUrl: "/files/resume-2.pdf",
        },
        {
          id: "resume-3",
          name: "Full Stack Developer Resume",
          description: "Comprehensive resume highlighting both frontend and backend skills for full stack positions.",
          createdAt: "2023-04-05",
          updatedAt: "2023-04-05",
          fileUrl: "/files/resume-3.pdf",
        },
      ],
      coverLetters: [
        {
          id: "cover-letter-1",
          name: "Tech Innovations Application",
          description: "Cover letter for Senior Frontend Developer position at Tech Innovations Inc.",
          createdAt: "2023-01-20",
          updatedAt: "2023-01-20",
          fileUrl: "/files/cover-letter-1.pdf",
        },
        {
          id: "cover-letter-2",
          name: "General Cover Letter",
          description: "Generic cover letter template that can be customized for different applications.",
          createdAt: "2023-02-15",
          updatedAt: "2023-03-10",
          fileUrl: "/files/cover-letter-2.pdf",
        },
      ],
    }
  }
  
  export function getUserApplications() {
    return [
      {
        id: "application-1",
        jobTitle: "Senior Frontend Developer",
        company: "Innovative Tech Solutions",
        location: "San Francisco, CA (Remote)",
        appliedDate: "2023-04-10",
        status: "interview",
        nextStep: "Technical Interview",
        nextStepDate: "2023-04-25",
        resumeUsed: "Software Developer Resume",
        coverLetterUsed: "Tech Innovations Application",
      },
      {
        id: "application-2",
        jobTitle: "UI/UX Developer",
        company: "Creative Design Agency",
        location: "New York, NY",
        appliedDate: "2023-04-05",
        status: "assessment",
        nextStep: "Technical Assessment",
        nextStepDate: "2023-04-15",
        resumeUsed: "UI/UX Focused Resume",
        coverLetterUsed: "General Cover Letter",
      },
      {
        id: "application-3",
        jobTitle: "Full Stack Engineer",
        company: "Tech Startup Inc.",
        location: "Austin, TX (Hybrid)",
        appliedDate: "2023-03-28",
        status: "applied",
        nextStep: null,
        nextStepDate: null,
        resumeUsed: "Full Stack Developer Resume",
        coverLetterUsed: null,
      },
      {
        id: "application-4",
        jobTitle: "Frontend Developer",
        company: "E-commerce Platform",
        location: "Seattle, WA (Remote)",
        appliedDate: "2023-03-20",
        status: "rejected",
        nextStep: null,
        nextStepDate: null,
        resumeUsed: "Software Developer Resume",
        coverLetterUsed: "General Cover Letter",
      },
      {
        id: "application-5",
        jobTitle: "React Developer",
        company: "Financial Tech Company",
        location: "Chicago, IL",
        appliedDate: "2023-03-15",
        status: "offer",
        nextStep: "Review Offer",
        nextStepDate: "2023-04-20",
        resumeUsed: "Software Developer Resume",
        coverLetterUsed: "General Cover Letter",
      },
    ]
  }
  
  export function getUserSavedJobs() {
    return [
      {
        id: "saved-job-1",
        title: "Senior React Developer",
        company: "Tech Innovations Inc.",
        location: "San Francisco, CA (Remote)",
        salary: "$120,000 - $150,000",
        postedDate: "2023-04-05",
        description: "We are looking for a Senior React Developer to join our team...",
        savedDate: "2023-04-10",
      },
      {
        id: "saved-job-2",
        title: "Frontend Engineer",
        company: "Software Solutions LLC",
        location: "New York, NY (Hybrid)",
        salary: "$110,000 - $140,000",
        postedDate: "2023-04-03",
        description: "Join our team as a Frontend Engineer to build responsive web applications...",
        savedDate: "2023-04-08",
      },
      {
        id: "saved-job-3",
        title: "UI/UX Developer",
        company: "Design Agency",
        location: "Los Angeles, CA",
        salary: "$100,000 - $130,000",
        postedDate: "2023-04-01",
        description: "Looking for a UI/UX Developer with strong design skills...",
        savedDate: "2023-04-07",
      },
      {
        id: "saved-job-4",
        title: "Full Stack JavaScript Developer",
        company: "Tech Startup",
        location: "Austin, TX (Remote)",
        salary: "$115,000 - $145,000",
        postedDate: "2023-03-30",
        description: "Join our growing team as a Full Stack JavaScript Developer...",
        savedDate: "2023-04-05",
      },
      {
        id: "saved-job-5",
        title: "React Native Developer",
        company: "Mobile App Company",
        location: "Seattle, WA",
        salary: "$125,000 - $155,000",
        postedDate: "2023-03-28",
        description: "We're seeking a React Native Developer to help build our mobile applications...",
        savedDate: "2023-04-02",
      },
      {
        id: "saved-job-6",
        title: "Frontend Team Lead",
        company: "E-commerce Platform",
        location: "Chicago, IL (Hybrid)",
        salary: "$140,000 - $170,000",
        postedDate: "2023-03-25",
        description: "Looking for a Frontend Team Lead to manage our development team...",
        savedDate: "2023-03-30",
      },
      {
        id: "saved-job-7",
        title: "JavaScript Developer",
        company: "Financial Tech",
        location: "Boston, MA",
        salary: "$105,000 - $135,000",
        postedDate: "2023-03-22",
        description: "Join our team as a JavaScript Developer to build web applications...",
        savedDate: "2023-03-28",
      },
      {
        id: "saved-job-8",
        title: "Senior Web Developer",
        company: "Healthcare Tech",
        location: "Denver, CO (Remote)",
        salary: "$130,000 - $160,000",
        postedDate: "2023-03-20",
        description: "We are looking for a Senior Web Developer to join our healthcare technology team...",
        savedDate: "2023-03-25",
      },
    ]
  }
  
  